### ISSUE TITLE
希望API返回的帖子内容能用beatifulsoap之类的处理一下👀

### ISSUE THREAD

**Issue by shaonianG** [WendaoLee/doubansaver#4]
http://asoul.otterdaily.cn:9000/api/getmailInfo/1
比如这个接口，返回的是整个html的字符串，希望可以用beautifulsoap处理一下变成比较好处理的格式

**Comment by WendaoLee** [comment]
嗯......我处理一下，按照这样的JSON格式返回如何？
```javascript
{
    "title": "集中楼xxxx",
    "author": "xxx",
    "content": "xxxx",
    "reply": [
        {
            "author":"reply one's name",
            "avatar":"https://douban.....头像的链接",
            "profile":"https://....主页链接",
            "content":"reply content",
            "time":"reply time"
        }
    ]
}
```
不过可能会推迟晚一点做。如果要加上这个处理我还要写一下缓存方面的功能。

**Comment by shaonianG** [comment]
> 嗯......我处理一下，按照这样的JSON格式返回如何？
> 
> ```js
> {
>     "title": "集中楼xxxx",
>     "author": "xxx",
>     "content": "xxxx",
>     "reply": [
>         {
>             "author":"reply one's name",
>             "avatar":"https://douban.....头像的链接",
>             "profile":"https://....主页链接",
>             "content":"reply content",
>             "time":"reply time"
>         }
>     ]
> }
> ```
> 
> 不过可能会推迟晚一点做。如果要加上这个处理我还要写一下缓存方面的功能。

也可以不用急着做，我刚刚查了下js也有处理html的办法，可以直接转成dom，也许我这边更方便🤔

**Comment by shaonianG** [comment]
也可以不用急着做，我刚刚查了下js也有处理html的办法，可以直接转成dom，也许我这边更方便🤔

**Comment by WendaoLee** [comment]
> 也可以不用急着做，我刚刚查了下js也有处理html的办法，可以直接转成dom，也许我这边更方便🤔

okk，如果你最后懒得做了跟我说一下233
需要注意的是，对于多页的帖子（超过100条回复的帖子），它的后页回复是嵌套的（这是我在存档时候的处理的逻辑没写好造成的，虽然并不影响最终内容）。

比如说这个帖子[http://asoul.otterdaily.cn:9900/mail/11](http://asoul.otterdaily.cn:9900/mail/11)，它的邮件html原内容从`br`标签之后开始（参见[对应的模板](https://github.com/WendaoLee/doubansaver/blob/main/oriFrontEnd/templates/mail.html)），主体内容从`<div class="topic-content clearfix" id="topic-content">`这个div标签开始，而后按照这样的嵌套下来：
```html
--- <div id="dale_group_topic_banner_after_content"> 
---- <div id="replysect">  
-----<div id="dale_group_topic_banner_after_content"> 
------<div id="replysect">  
...
```
嗯，必须承认当时写得很草率没有考虑太多细节性的东西。
你也可以去看ZhijiangSaver的相关处理源码（虽然写得很丑）了解整个大致的架构。

**Comment by shaonianG** [comment]
今天抽出时间看了下js转化html的，好像没有那么好用的😔还是得拜托你那边处理一下返回

**Comment by WendaoLee** [comment]
> 今天抽出时间看了下js转化html的，好像没有那么好用的😔还是得拜托你那边处理一下返回

okk。不过你可能要等上大概一个月时间了🤣这一个月我有两个比赛和一个大作业。

**Comment by WendaoLee** [comment]
存档姬停止维护了。感谢您之前想要帮忙的意愿。
